import Config

# Configure your database
config :garage, Garage.Repo,
  # For development, we disable any cache and enable
  # debugging and code reloading.
  #
  # The watchers configuration can be used to run external
  # watchers to your application. For example, we can use it
  # to bundle .js and .css sources.
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "garage_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :garage, GarageWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "Ff9tytUGu/iBg5dFiHE+rkHE0ATaZecHTADEgBm7tQOniQmVOFv6Cq5/kAKck5D6",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:default, ~w(--watch)]}
  ]

# Watch static and templates for browser reloading.
config :garage, GarageWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/garage_web/(controllers|live|components)/.*(ex|heex)$",
      # ## SSL Support
      #
      # In order to use HTTPS in development, a self-signed
      # certificate can be generated by running the following
      # Mix task:
      ~r"lib/garage_web/pyro_overrides.ex"
    ]
  ]

# Enable dev routes for dashboard and mailbox
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
config :garage, dev_routes: true

config :garage,
  upload_bucket: :dev,
  public_image_root: "https://pub-09d9519a20aa4503bc4336772b724d1a.r2.dev",
  discord_channel: 1_388_349_484_383_207_516,
  site_url: "http://localhost:4000"

# Do not include metadata nor timestamps in development logs
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
config :logger, :console, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
config :phoenix, :plug_init_mode, :runtime

# Set a higher stacktrace during development. Avoid configuring such
# different ports.

# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Include HEEx debug annotations as HTML comments in rendered markup
config :phoenix_live_view, :debug_heex_annotations, true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

import_config("dev.secret.exs")
