import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :garage, GarageWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Garage.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
config :garage,
  upload_bucket: :prod,
  public_image_root: "https://pics.moped.build"

config :ex_aws,
  region: "auto"

config :ex_aws, :s3,
  scheme: "https",
  host: "4e7e19d415ae25f4681ff5aa75b38d98.r2.cloudflarestorage.com/prod"
