defmodule Garage.Repo.Migrations.AddImageUrlsToBuilds do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:builds) do
      add :image_urls, {:array, :text}, default: []
    end
  end

  def down do
    alter table(:builds) do
      remove :image_urls
    end
  end
end