defmodule Garage.Repo.Migrations.UpdateBuilds do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :updated_at, :utc_datetime
      modify :inserted_at, :utc_datetime
    end

    alter table(:models) do
      modify :updated_at, :utc_datetime
      modify :inserted_at, :utc_datetime
    end

    alter table(:makes) do
      modify :updated_at, :utc_datetime
      modify :inserted_at, :utc_datetime
    end

    alter table(:likes) do
      modify :updated_at, :utc_datetime
      modify :inserted_at, :utc_datetime
    end

    rename table(:builds), :make, to: :make_id

    rename table(:builds), :model, to: :model_id

    alter table(:builds) do
      modify :updated_at, :utc_datetime
      modify :inserted_at, :utc_datetime

      add :model_id,
          references(:models,
            column: :id,
            name: "builds_model_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:builds, "builds_model_id_fkey")

    alter table(:builds) do
      remove :model_id
      modify :inserted_at, :utc_datetime_usec
      modify :updated_at, :utc_datetime_usec
    end

    rename table(:builds), :model_id, to: :model

    rename table(:builds), :make_id, to: :make

    alter table(:likes) do
      modify :inserted_at, :utc_datetime_usec
      modify :updated_at, :utc_datetime_usec
    end

    alter table(:makes) do
      modify :inserted_at, :utc_datetime_usec
      modify :updated_at, :utc_datetime_usec
    end

    alter table(:models) do
      modify :inserted_at, :utc_datetime_usec
      modify :updated_at, :utc_datetime_usec
    end

    alter table(:users) do
      modify :inserted_at, :utc_datetime_usec
      modify :updated_at, :utc_datetime_usec
    end
  end
end