defmodule Garage.Repo.Migrations.AddIndices do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:wheels, [:manufacturer_id, :name], name: "wheels_name_index")

    create unique_index(:variators, [:manufacturer_id, :name], name: "variators_name_index")

    create unique_index(:pulleys, [:manufacturer_id, :name], name: "pulleys_name_index")

    create unique_index(:ignitions, [:manufacturer_id, :name], name: "ignitions_name_index")

    create unique_index(:forks, [:manufacturer_id, :name], name: "forks_name_index")

    create unique_index(:exhausts, [:manufacturer_id, :name], name: "exhausts_name_index")

    create unique_index(:engines, [:manufacturer_id, :name], name: "engines_name_index")

    create unique_index(:cylinders, [:manufacturer_id, :name], name: "cylinders_name_index")

    create unique_index(:cranks, [:manufacturer_id, :name], name: "cranks_name_index")

    create unique_index(:clutches, [:manufacturer_id, :name], name: "clutches_name_index")

    create unique_index(:carburetors, [:manufacturer_id, :name], name: "carburetors_name_index")
  end

  def down do
    drop_if_exists unique_index(:carburetors, [:manufacturer_id, :name],
                     name: "carburetors_name_index"
                   )

    drop_if_exists unique_index(:clutches, [:manufacturer_id, :name], name: "clutches_name_index")

    drop_if_exists unique_index(:cranks, [:manufacturer_id, :name], name: "cranks_name_index")

    drop_if_exists unique_index(:cylinders, [:manufacturer_id, :name],
                     name: "cylinders_name_index"
                   )

    drop_if_exists unique_index(:engines, [:manufacturer_id, :name], name: "engines_name_index")

    drop_if_exists unique_index(:exhausts, [:manufacturer_id, :name], name: "exhausts_name_index")

    drop_if_exists unique_index(:forks, [:manufacturer_id, :name], name: "forks_name_index")

    drop_if_exists unique_index(:ignitions, [:manufacturer_id, :name],
                     name: "ignitions_name_index"
                   )

    drop_if_exists unique_index(:pulleys, [:manufacturer_id, :name], name: "pulleys_name_index")

    drop_if_exists unique_index(:variators, [:manufacturer_id, :name],
                     name: "variators_name_index"
                   )

    drop_if_exists unique_index(:wheels, [:manufacturer_id, :name], name: "wheels_name_index")
  end
end