defmodule Garage.Repo.Migrations.MakeAndModelRequired do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:builds) do
      modify :model_id, :uuid, null: false
      modify :make_id, :uuid, null: false
      modify :image_urls, {:array, :text}, null: false
    end
  end

  def down do
    alter table(:builds) do
      modify :image_urls, {:array, :text}, null: true
      modify :make_id, :uuid, null: true
      modify :model_id, :uuid, null: true
    end
  end
end