defmodule Garage.Repo.Migrations.AddAvatarToUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :updated_at, :utc_datetime_usec
      modify :inserted_at, :utc_datetime_usec
      add :avatar_url, :text
    end

    alter table(:tokens) do
      modify :created_at, :utc_datetime_usec
      modify :updated_at, :utc_datetime_usec
    end

    alter table(:models) do
      modify :updated_at, :utc_datetime_usec
      modify :inserted_at, :utc_datetime_usec
    end

    alter table(:makes) do
      modify :updated_at, :utc_datetime_usec
      modify :inserted_at, :utc_datetime_usec
    end

    alter table(:likes) do
      modify :updated_at, :utc_datetime_usec
      modify :inserted_at, :utc_datetime_usec
    end

    alter table(:comments) do
      modify :updated_at, :utc_datetime_usec
      modify :inserted_at, :utc_datetime_usec
    end

    alter table(:builds) do
      modify :updated_at, :utc_datetime_usec
      modify :inserted_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:builds) do
      modify :inserted_at, :utc_datetime
      modify :updated_at, :utc_datetime
    end

    alter table(:comments) do
      modify :inserted_at, :utc_datetime
      modify :updated_at, :utc_datetime
    end

    alter table(:likes) do
      modify :inserted_at, :utc_datetime
      modify :updated_at, :utc_datetime
    end

    alter table(:makes) do
      modify :inserted_at, :utc_datetime
      modify :updated_at, :utc_datetime
    end

    alter table(:models) do
      modify :inserted_at, :utc_datetime
      modify :updated_at, :utc_datetime
    end

    alter table(:tokens) do
      modify :updated_at, :utc_datetime
      modify :created_at, :utc_datetime
    end

    alter table(:users) do
      remove :avatar_url
      modify :inserted_at, :utc_datetime
      modify :updated_at, :utc_datetime
    end
  end
end