defmodule Garage.Repo.Migrations.UpdateMakeAndModel do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:models) do
      modify :description, :text, default: ""
    end

    alter table(:makes) do
      modify :description, :text, null: true, default: ""
    end
  end

  def down do
    alter table(:makes) do
      modify :description, :text, null: false, default: nil
    end

    alter table(:models) do
      modify :description, :text, default: nil
    end
  end
end