defmodule Garage.Repo.Migrations.FixIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:models, [:slug], name: "models_slug_index")

    create unique_index(:models, [:make_id, :slug], name: "models_slug_index")
  end

  def down do
    drop_if_exists unique_index(:models, [:make_id, :slug], name: "models_slug_index")

    create unique_index(:models, [:slug], name: "models_slug_index")
  end
end