defmodule Garage.Repo.Migrations.AddYearToBuilds do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:builds) do
      add :year, :bigint, null: false
    end
  end

  def down do
    alter table(:builds) do
      remove :year
    end
  end
end