defmodule Garage.Repo.Migrations.UpdateDataModel do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:engines) do
      add :transmission, :text
    end

    alter table(:cylinders) do
      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      # remove :engine_id

      add :bore, :bigint
    end

    alter table(:cranks) do
      add :conn_rod_length, :bigint
      add :small_end_bearing_diameter, :bigint
    end

    alter table(:carburetors) do
      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      # remove :size

      modify :jets, {:array, :text}, default: nil
    end
  end

  def down do
    alter table(:carburetors) do
      modify :jets, {:array, :text}, default: []
      # This is the `down` migration of the statement:
      #
      #     remove :size
      #

      # add :size, :text
    end

    alter table(:cranks) do
      remove :small_end_bearing_diameter
      remove :conn_rod_length
    end

    alter table(:cylinders) do
      remove :bore
      # This is the `down` migration of the statement:
      #
      #     remove :engine_id
      #

      # add :engine_id, references(:engines, column: :id, name: "cylinders_engine_id_fkey", type: :uuid, prefix: "public")
    end

    alter table(:engines) do
      remove :transmission
    end
  end
end