defmodule Garage.Repo.Migrations.AddRollerSizeToVariators do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:variators) do
      add :roller_size, :text
    end
  end

  def down do
    alter table(:variators) do
      remove :roller_size
    end
  end
end
