defmodule Garage.Repo.Migrations.AddEngineTuning do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:engines) do
      add :drive, {:array, :text}
    end

    create table(:engine_tunings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :transmission, :text
      add :drive, {:array, :text}
      add :front_sprocket, :bigint
      add :rear_sprocket, :bigint
      add :gear_ratio, :text

      add :engine_id,
          references(:engines,
            column: :id,
            name: "engine_tunings_engine_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :build_id,
          references(:builds,
            column: :id,
            name: "engine_tunings_build_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:carb_tunings) do
      modify :size, :text
    end

    alter table(:builds) do
      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      remove :engine_id

      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      remove :gear_ratio

      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      remove :rear_sprocket

      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      remove :front_sprocket

      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      remove :transmission

      add :engine_tuning_id,
          references(:engine_tunings,
            column: :id,
            name: "builds_engine_tuning_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:builds, "builds_engine_tuning_id_fkey")

    alter table(:builds) do
      remove :engine_tuning_id
      # This is the `down` migration of the statement:
      #
      #     remove :transmission
      #

      add :transmission, :text
      # This is the `down` migration of the statement:
      #
      #     remove :front_sprocket
      #

      add :front_sprocket, :bigint
      # This is the `down` migration of the statement:
      #
      #     remove :rear_sprocket
      #

      add :rear_sprocket, :bigint
      # This is the `down` migration of the statement:
      #
      #     remove :gear_ratio
      #

      add :gear_ratio, :text
      # This is the `down` migration of the statement:
      #
      #     remove :engine_id
      #

      add :engine_id,
          references(:engines,
            column: :id,
            name: "builds_engine_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:carb_tunings) do
      modify :size, :bigint
    end

    drop constraint(:engine_tunings, "engine_tunings_engine_id_fkey")

    drop constraint(:engine_tunings, "engine_tunings_build_id_fkey")

    drop table(:engine_tunings)

    alter table(:engines) do
      remove :drive
    end
  end
end
