defmodule Garage.Repo.Migrations.AddFieldsToVariators do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:variators) do
      add :type, :text, null: false, default: "rollers"
      add :rollers, :bigint
    end

    alter table(:cylinders) do
      modify :displacement, :bigint, default: nil
    end

    alter table(:carb_tunings) do
      modify :tuning, :map, default: %{}
    end
  end

  def down do
    alter table(:carb_tunings) do
      modify :tuning, :map, default: nil
    end

    alter table(:cylinders) do
      modify :displacement, :bigint, default: 50
    end

    alter table(:variators) do
      remove :rollers
      remove :type
    end
  end
end
