defmodule Garage.Repo.Migrations.DataUpdates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:variator_tunings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :weights, {:array, :float}, default: []

      add :variator_id,
          references(:variators,
            column: :id,
            name: "variator_tunings_variator_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :build_id,
          references(:builds,
            column: :id,
            name: "variator_tunings_build_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:ignition_tunings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :timing, :bigint
      add :timing_method, :text
      add :cdi_box, :text

      add :ignition_id,
          references(:ignitions,
            column: :id,
            name: "ignition_tunings_ignition_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :build_id,
          references(:builds,
            column: :id,
            name: "ignition_tunings_build_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:cylinder_tunings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :blowdown, :text
      add :port_map_url, :text

      add :cylinder_id,
          references(:cylinders,
            column: :id,
            name: "cylinder_tunings_cylinder_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :build_id,
          references(:builds,
            column: :id,
            name: "cylinder_tunings_build_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:clutch_tunings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :springs, :text

      add :clutch_id,
          references(:clutches,
            column: :id,
            name: "clutch_tunings_clutch_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :build_id,
          references(:builds,
            column: :id,
            name: "clutch_tunings_build_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:builds) do
      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      remove :variator_id

      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      remove :clutch_id

      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      remove :cylinder_id

      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      remove :ignition_id

      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      remove :variated?

      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      remove :cdi_box

      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      remove :subframe

      add :transmission, :text

      add :ignition_tuning_id,
          references(:ignition_tunings,
            column: :id,
            name: "builds_ignition_tuning_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :cylinder_tuning_id,
          references(:cylinder_tunings,
            column: :id,
            name: "builds_cylinder_tuning_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :variator_tuning_id,
          references(:variator_tunings,
            column: :id,
            name: "builds_variator_tuning_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :clutch_tuning_id,
          references(:clutch_tunings,
            column: :id,
            name: "builds_clutch_tuning_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:builds, "builds_ignition_tuning_id_fkey")

    drop constraint(:builds, "builds_cylinder_tuning_id_fkey")

    drop constraint(:builds, "builds_variator_tuning_id_fkey")

    drop constraint(:builds, "builds_clutch_tuning_id_fkey")

    alter table(:builds) do
      remove :clutch_tuning_id
      remove :variator_tuning_id
      remove :cylinder_tuning_id
      remove :ignition_tuning_id
      remove :transmission
      # This is the `down` migration of the statement:
      #
      #     remove :subframe
      #

      add :subframe, :text
      # This is the `down` migration of the statement:
      #
      #     remove :cdi_box
      #

      add :cdi_box, :text
      # This is the `down` migration of the statement:
      #
      #     remove :variated?
      #

      add :variated?, :boolean, null: false, default: false
      # This is the `down` migration of the statement:
      #
      #     remove :ignition_id
      #

      add :ignition_id,
          references(:ignitions,
            column: :id,
            name: "builds_ignition_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      # This is the `down` migration of the statement:
      #
      #     remove :cylinder_id
      #

      add :cylinder_id,
          references(:cylinders,
            column: :id,
            name: "builds_cylinder_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      # This is the `down` migration of the statement:
      #
      #     remove :clutch_id
      #

      add :clutch_id,
          references(:clutches,
            column: :id,
            name: "builds_clutch_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      # This is the `down` migration of the statement:
      #
      #     remove :variator_id
      #

      add :variator_id,
          references(:variators,
            column: :id,
            name: "builds_variator_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    drop constraint(:clutch_tunings, "clutch_tunings_clutch_id_fkey")

    drop constraint(:clutch_tunings, "clutch_tunings_build_id_fkey")

    drop table(:clutch_tunings)

    drop constraint(:cylinder_tunings, "cylinder_tunings_cylinder_id_fkey")

    drop constraint(:cylinder_tunings, "cylinder_tunings_build_id_fkey")

    drop table(:cylinder_tunings)

    drop constraint(:ignition_tunings, "ignition_tunings_ignition_id_fkey")

    drop constraint(:ignition_tunings, "ignition_tunings_build_id_fkey")

    drop table(:ignition_tunings)

    drop constraint(:variator_tunings, "variator_tunings_variator_id_fkey")

    drop constraint(:variator_tunings, "variator_tunings_build_id_fkey")

    drop table(:variator_tunings)
  end
end
