defmodule Garage.Repo.Migrations.SetNotNullPulley do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:pulleys) do
      modify :sizes, {:array, :bigint}, null: true
    end
  end

  def down do
    alter table(:pulleys) do
      modify :sizes, {:array, :bigint}, null: false
    end
  end
end
