defmodule Garage.Repo.Migrations.AddSlugToEngine do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:engines) do
      add :slug, :text, null: true
    end
  end

  def down do
    alter table(:engines) do
      remove :slug
    end
  end
end
