defmodule Garage.Repo.Migrations.AddSizeToCarburetor do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:models) do
      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      remove :stock_wheels_id
      # 
      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      remove :stock_forks_id
    end

    # 
    alter table(:carburetors) do
      add :sizes, {:array, :text}, default: []
    end

    alter table(:builds) do
      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      remove :forks_id
      # 
      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      remove :wheels_id
    end

    # 
  end

  def down do
    alter table(:builds) do
      # This is the `down` migration of the statement:
      #
      #     remove :wheels_id
      #
      # 
      add :wheels_id,
          references(:wheels,
            column: :id,
            name: "builds_wheels_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      # This is the `down` migration of the statement:
      #
      #    remove :forks_id
      #
      # 
      add :forks_id,
          references(:forks,
            column: :id,
            name: "builds_forks_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    # 
    alter table(:carburetors) do
      remove :sizes
    end

    alter table(:models) do
      # This is the `down` migration of the statement:
      #
      #     remove :stock_forks_id
      #
      # 
      add :stock_forks_id,
          references(:forks,
            column: :id,
            name: "models_stock_forks_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      # This is the `down` migration of the statement:
      #
      #     remove :stock_wheels_id
      #
      # 
      add :stock_wheels_id,
          references(:wheels,
            column: :id,
            name: "models_stock_wheels_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    # 
  end
end
