defmodule Garage.Repo.Migrations.IdentityOnName do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:variators) do
      modify :size, :bigint, null: true
    end

    create unique_index(:manufacturers, [:name], name: "manufacturers_name_index")
  end

  def down do
    drop_if_exists unique_index(:manufacturers, [:name], name: "manufacturers_name_index")

    alter table(:variators) do
      modify :size, :bigint, null: false
    end
  end
end
