defmodule Garage.Repo.Migrations.ChangeWeightsToString do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:variator_tunings) do
      modify :weights, {:array, :text}
    end

    alter table(:engines) do
      modify :drive, {:array, :text}, default: []
    end

    alter table(:engine_tunings) do
      modify :drive, {:array, :text}
    end
  end

  def down do
    alter table(:engine_tunings) do
      modify :drive, :text
    end

    alter table(:engines) do
      modify :drive, {:array, :text}, default: nil
    end

    alter table(:variator_tunings) do
      modify :weights, {:array, :float}
    end
  end
end
