defmodule Garage.Repo.Migrations.AddSizeToCarbTuning do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:carb_tunings) do
      add :size, :text
    end
  end

  def down do
    alter table(:carb_tunings) do
      remove :size
    end
  end
end
