defmodule Garage.Repo.Migrations.AddPushToken do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:push_tokens, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :endpoint, :text, null: false
      add :expiration_time, :utc_datetime
      add :keys, :map, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "push_tokens_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:images) do
      modify :index, :bigint, null: false
    end
  end

  def down do
    alter table(:images) do
      modify :index, :bigint, null: true
    end

    drop constraint(:push_tokens, "push_tokens_user_id_fkey")

    drop table(:push_tokens)
  end
end
