defmodule Garage.Repo.Migrations.AddClubsAndMemberships do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "memberships_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :club_id, :uuid
    end

    create table(:clubs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:memberships) do
      modify :club_id,
             references(:clubs,
               column: :id,
               name: "memberships_club_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:clubs) do
      add :name, :text, null: false
      add :city, :text, null: false
      add :state, :text, null: false
      add :country, :text, null: false
      add :logo_url, :text
      add :icon_url, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:clubs) do
      remove :updated_at
      remove :inserted_at
      remove :icon_url
      remove :logo_url
      remove :country
      remove :state
      remove :city
      remove :name
    end

    drop constraint(:memberships, "memberships_club_id_fkey")

    alter table(:memberships) do
      modify :club_id, :uuid
    end

    drop table(:clubs)

    drop constraint(:memberships, "memberships_user_id_fkey")

    drop table(:memberships)
  end
end
