defmodule Garage.Repo.Migrations.AddImagesToBuilds do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:variator_tunings) do
      remove :build_id
    end

    create table(:images, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :original_url, :text, null: false
      add :thumbnail_url, :text
      add :optimized_url, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :build_id,
          references(:builds,
            column: :id,
            name: "images_build_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    alter table(:ignition_tunings) do
      remove :build_id
    end

    drop_if_exists unique_index(:engines, [:slug], name: "engines_slug_index")

    alter table(:engine_tunings) do
      remove :build_id
    end

    alter table(:cylinder_tunings) do
      remove :build_id
    end

    alter table(:clutch_tunings) do
      remove :build_id
    end

    alter table(:carb_tunings) do
      remove :build_id
    end
  end

  def down do
    alter table(:carb_tunings) do
      add :build_id,
          references(:builds,
            column: :id,
            name: "carb_tunings_build_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:clutch_tunings) do
      add :build_id,
          references(:builds,
            column: :id,
            name: "clutch_tunings_build_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:cylinder_tunings) do
      add :build_id,
          references(:builds,
            column: :id,
            name: "cylinder_tunings_build_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:engine_tunings) do
      add :build_id,
          references(:builds,
            column: :id,
            name: "engine_tunings_build_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:engines, [:slug], name: "engines_slug_index")

    alter table(:ignition_tunings) do
      add :build_id,
          references(:builds,
            column: :id,
            name: "ignition_tunings_build_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    drop constraint(:images, "images_build_id_fkey")

    drop table(:images)

    alter table(:variator_tunings) do
      add :build_id,
          references(:builds,
            column: :id,
            name: "variator_tunings_build_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end
end
