defmodule Garage.Repo.Migrations.AddIndexToImages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:images) do
      modify :build_id, :uuid, null: false
      add :index, :bigint
    end
  end

  def down do
    alter table(:images) do
      remove :index
      modify :build_id, :uuid, null: true
    end
  end
end
