defmodule Garage.Repo.Migrations.MakePushTokenEndpointUnique do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:push_tokens, [:endpoint], name: "push_tokens_endpoint_index")
  end

  def down do
    drop_if_exists unique_index(:push_tokens, [:endpoint], name: "push_tokens_endpoint_index")
  end
end
